services:
  - type: web
    name: bitunix-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4
    envVars:
      - key: API_KEY
        value: ${API_KEY}
      - key: API_SECRET
        value: ${API_SECRET}
      - key: EMAIL_SENDER
        value: ${EMAIL_SENDER}
      - key: EMAIL_PASSWORD
        value: ${EMAIL_PASSWORD}
